security:
  oauth2:
    client:
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      clientAuthenticationScheme: form
      clientId: 1009700773461-fc1leqha280auu2duur3f2edoluteo0v.apps.googleusercontent.com
      clientSecret: ePVBJ3JAWx10yMXT7mFuV-0S
      scope: openid, email, profile
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
      preferTokenInfo: 'true'
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
